### ISSUE TITLE
Use of if ... else with digitalWriteFast

### ISSUE THREAD

**Issue by JanvdZanden** [mpflaga/Arduino-digitalWriteFast#1]
You can use the construct

if ( condition1 )
  digitalWrite(pin1, HIGH);
else
  digitalWrite(pin1, LOW);

But you cannot use this construct with digitalWriteFast() due to the expansion of a macro.
You need to write de digitalWriteFast()  within brackets {  and }

So write:

if ( condition1 )
{
  digitalWriteFast(pin1, HIGH);
}
else
{
  digitalWriteFast(pin1, LOW);
}

I think this is very relevant for the user manual/ReadMe.txt, because unexperienced users will get very confused with the error message..

Thanks for the lib.

**Comment by JanvdZanden** [comment]
I use the Arduino to control 32 bit (and later on 48 bit) digital Input/Output via 4 (later 6) pieces of 74HC595 and 74HC165.
My serial data transmission of 32 bits to and from  these ports is made in the main loop and required 0,7 ms. with the normal digitalWrite function. Too long.
With the digitalWriteFast function it has been shrunken to only 0,2 ms.
Now it is possible to connect this to a 1 ms. Timer interrupt so that I have 32 (48) stable PWM outputs for controlling analogue hobby trains with natural velocity control in 16 (or more if I wish) voltage steps.
Thanks for this enormous improvement of digitalWrite (that has really a very poor Arduino implementation).
At what time will this digitalWriteFast be available in the standard Arduino Library? It is ridiculous that users have to bother with this poor I/O performance, where an excellent, hardware independent (!), solution is at hand!! Why does a discussion about this tissue lasts for more than 5 years without a decision?

**Comment by mpflaga** [comment]
I appreciate your comment. While I am not maintaining this repo, I believe it would make a great addition to in an example file, demonstrating your observation. 

I suppose an interested party who was available to properly maintain the repo could properly format the library as a IDE compliant library and submit it to the Library Manager.

That said a quick search of the IDE Library Manager of the word "fast digital" show several similar projects; DigitalIO, DIO2, FastsGPIO, Pin, etc... which I believe would be supported.

thanks for you feed back.
